### ISSUE TITLE
Unsafe access by index may panic

### ISSUE THREAD

**Issue by kpcyrd** [krolaw/dhcp4r#6]
I've fuzzed [sniffglue] with [cargo-fuzz] for a couple of days and it discovered a panic in the packet processing. The panic occures inside dhcp4r, which is used for dhcp decoding. The problem seems to be an out of range access in `dhcp4r::packet::decode`.

The packet that triggers the bug can be found here: https://github.com/kpcyrd/sniffglue/issues/16

You may want to look into [nom], as it's easier to decode packets and you get length checks for free. :)

[sniffglue]: https://github.com/kpcyrd/sniffglue
[cargo-fuzz]: https://github.com/rust-fuzz/cargo-fuzz
[nom]: https://github.com/Geal/nom

**Comment by krolaw** [comment]
I suggest adding check in the packet function ensuring the message length is at least 240 bytes.

**Comment by lkolbly** [comment]
This should fixed in 0.2.0 (we use nom now), I've made a PR to update sniffglue: kpcyrd/sniffglue#61
